# miniconda bootstrap from conda-forge recipe
matrix:
  fast_finish: true

environment:
  matrix:
    - CONDA_PY: 36
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

platform:
  - x64

build: off

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set show_channel_urls true
  - cmd: conda config --add channels conda-forge
  #- cmd: conda update --yes --quiet conda
  - cmd: conda install -y pyzmq tornado jupyter_client nbformat ipykernel pip nodejs nose
  # not using `conda install -y` on nbconvent package because there is
  # currently a bug with the version that the anaconda installs, so we will just install it with pip
  - cmd: pip install nbconvert
  - cmd: python setup.py build
  - cmd: pip install .[test]

test_script:
  - nosetests  -v notebook --exclude-dir notebook\tests\selenium
